### PR TITLE
Add call to Hedwig.Robot.handle_connect on :connected callback

### PR DESCRIPTION
**Pull request by PhillippOhlandt**
Otherwise the `handle_connect/1` function in the robot module never gets called and the bot won't be registered by it's name (when using the default robot module setup).

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
@jeffweiss I resolved the merge conflicts using GitHubs UI. The PR diff looks good to me, but I still see the `This branch has conflicts that must be resolved` message.

**Comment by PhillippOhlandt** [comment]
I did it again and now it works, lol.

EDIT: Or it's because you merged it before I resolved the conflicts again.

**Comment by jeffweiss** [comment]
Merged via 78551611ae22ec29a002d3cad3fe6b5e801f4986

**Comment by jeffweiss** [comment]
Deployed in 0.1.4. Thanks!

**Pull request closed without merging**
